Rework the readmefirst entity.
SUSE/doc-cap pull request #1041
Opened 2020-12-07 11:41 UTC by KucharczykL

Remove the entity from the administrative notes section and change its
formatting to a regular list.

Closes #1032.

2020-12-07 22:26 UTC, btat requested changes

2020-12-07 22:26 UTC, btat commented on xml/repeated-content-decl.ent
> +        <link xlink:href="https://www.suse.com/releasenotes/x86_64/SUSE-CAP/1/">
Link should point to the 2.x RN

2020-12-07 22:28 UTC, btat commented
Let's fix the link and merge for now. There was additional feedback about moving this entire section, which we can discuss afterwards when we start on the restructure.

2020-12-09 11:35 UTC, KucharczykL commented
Fixed the link.

2020-12-09 17:44 UTC, btat approved these changes

2020-12-09 17:44 UTC, merged