Replace overly specific example with general advice.
SUSE/doc-cap pull request #964
Opened 2020-09-14 10:32 UTC by KucharczykL

Replaces the specific advice how to create a named MySQL/MariaDB database with general advice on where to find charts and their values.yaml file.

If we have other cases where the user is better off looking at the upstream instead of being given an example that is bound to break often, it's worth considering adding a summary section that would describe where to find information upstream. The section could be in the Deployment and Administration Notes or the Troubleshooting section.

2020-09-14 17:41 UTC, btat approved these changes

2020-09-14 17:42 UTC, btat requested changes

2020-09-14 17:42 UTC, btat commented on xml/cap_admin_service_broker.xml
> +     file in the upstream &helm; charts at https://github.com/helm/charts
<link> tag needed for the link

2020-09-15 10:19 UTC, KucharczykL commented on xml/cap_admin_service_broker.xml
> +     file in the upstream &helm; charts at https://github.com/helm/charts
Good call! Fixed.

2020-09-15 16:46 UTC, btat approved these changes

2020-09-15 16:47 UTC, merged